 # for git resources 
 
resources:
  - name: sample_jobQ 
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
#       files:
#         except: pipelines.yml
    version:
      sha: master

pipelines:
  - name: pipelinejob
    steps:
      - name: test1u16
        type: bash
        configuration:
          nodePool: kermit_ubuntu_pool
        triggeredBy:
          resources:
            - sample_jobQ
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - bump_semver v1.0.0 minor
            - compare_git --resource sample_jobQ
            - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
            - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ           
            - compare_git --path  $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ  --commit-range HEAD~2..HEAD
            - update_commit_status sample_jobQ --status processing --message “my_status_is pushed” --context $STEP_NAME

      - name: test2u18
        type: bash
        setup:
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18node
                tag: master
                options: "" 
#         configuration:
#           nodePool: kermit_ubuntu18_pool
        triggeredBy:
          steps:
            - test1u16
        requires:
          resources:
            - sample_jobQ 
        execution:
          onStart:
            - printenv
            - echo "starting now"
          onExecute:
            - printenv
            - bump_semver v1.0.0 minor
            - compare_git --resource sample_jobQ
            - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
            - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ 
#             - update_commit_status sample_jobQ --status success --message “my status push” --context $STEP_NAME
 
             
#       - name: test3c7
#         type: bash
# #         configuration:
# #           nodePool: kermit_centos_pool
#         setup:
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/c7node
#                 tag: master
#                 options: "" 
#         triggeredBy:
#           steps:
#             - test1u16
#         requires:
#           resources:
#             - sample_jobQ 
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
#             - docker images
#             - openssl genrsa -out key.pem 1024 
# #             - bump_semver v1.0.0 minor
# #             - compare_git --resource sample_jobQ
# #             - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
# #             - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ 
           
