 # for git resources 
 
resources:
  - name: sample_jobQ
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
    version:
      sha: master
      
pipelines:
  - name: pipelinejob
    steps:
      - name: test1
        type: bash
        setup: 
#           environmentVariables:
#             normal:
#               ENV1: value1 
          runtime:            
            type: image
            image:
              custom:
                name: bindushree16/u16node
                tag: master
                options: "--env Villa=good"
                autoPull: false
        triggeredBy:
          resources:
            - sample_jobQ
        execution:
          onExecute:
            - printenv
            - docker images
#             - add_run_variable keyName="valueTest"
#             - pushd $res_sample_jobQ_resourcePath
#             - save_run_state pipelines.yml my_file
#             - popd
#             - test "$ENV1" == "value1"
#             - echo "$ENV1" == "value1"
#             - ls -la
#             - sleep 2m

      - name: test2
        type: bash
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - printenv
#             - export_run_variables 
#             - restore_run_state my_file pipelines.yml
#             - test "$ENV1" == "value1"
#             - echo "$ENV1" == "value1" 

#       - name: test3
#         type: bash
#         configuration:
#           affinityGroup: kamal
#           nodePool: kermit_ubuntu18_pool       
#         setup:
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
#             - echo "hi"
