 # for git resources 
 
resources:
  - name: sample_jobQ 
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
#       buildOn:
#         commit: false
    version:
      sha: master

pipelines:
  - name: pipelinejob
    steps:
      - name: test1
        type: bash
#         configuration:
#           affinityGroup: kermit
#           nodePool: kermit_ubuntu_pool       
        setup: 
          runtime:            
            type: image
            image:
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        requires:
          resources:
            - sample_jobQ
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - bump_semver v1.0.0 patch

      - name: test2
        type: bash
#         configuration:
#           affinityGroup: kamal
#           nodePool: kermit_ubuntu18_pool
        setup:
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          steps:
            - test1
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            

#       - name: test3
#         type: bash
#         configuration:
#           affinityGroup: kermit
#           nodePool: kermit_ubuntu_pool 
#         setup:
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         requires:
#           steps:
#             - test1
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
#             - echo "hi"
