 # for git resources 
 
resources:
  - name: sample_jobQ
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
#       buildOn:
#         commit: false
    version:
      sha: master
   
pipelines:
  - name: pipelinejobbindu
    steps:
      - name: test3
        type: bash
        setup: 
#           environmentVariables:
#             normal:
#               ENV1: value1 
          runtime:            
            type: image
            image:
              custom:
                name: drydock/c7node #shippabledocker/u16phpall
                tag: test7.0
                options: "--env Villa=good"
#             #    autoPull: false
        triggeredBy:
          resources:
            - sample_jobQ
        execution:
          onExecute:
            - printenv
#             - sleep 2m
            - echo "hi"
#             - docker images
#             - add_run_variable keyName="valueTestUpdate"
#             - pushd $res_sample_jobQ_resourcePath
#             - save_run_state pipelines.yml my_file
# #             - popd
#             - test "$ENV1" == "value1"
#             - echo "$ENV1" == "value1"
# #             - ls -la
# #             - sleep 2m

      - name: test4
        type: bash
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - printenv
# #             - export_run_variables 
# #             - restore_run_state my_file pipelines.yml
#             - test "$keyName" == "valueTestUpdate"
#             - echo "$keyName" == "valueTestUpdate" 

#       - name: test3
#         type: bash
#         configuration:
#           affinityGroup: kamal
#           nodePool: kermit_ubuntu18_pool       
#         setup:
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
#             - echo "hi"
