 # for git resources 
 
resources:
  - name: sample_jobQ 
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
    version:
      sha: master

#   - name: sample_jobW
#     type: gitRepo
#     repoPath: bindushree16/jobIn
#     configuration:
#       integrationName: bindu_github
#       branches:
#         only: master
#     version:
#       sha: master     

pipelines:
  - name: pipelinejob1
    steps:
      - name: test1u16
        type: bash
        configuration:
          nodePool: kermit_ubuntu_pool
        setup:
          environmentVariables:
            normal:
              ENV1: value1
        requires:
          integrations:
            - slack_bindu      
        triggeredBy:
          resources:
            - sample_jobQ
        execution:
          onStart:
            - printenv
          onExecute: 
             - printenv
             - test $ENV1=value1
             - echo $ENV1=value1 
             - switch_env nodejs 8.16.0
             - printenv
#             - pwd
#             - pushd $res_sample_jobQ_resourcePath
#             - echo "$res_sample_jobQ_resourcePath"
#             - retry_command nod --version
#             - ls -la
#             - bump_semver v1.0.0 minor
#             - compare_git --resource sample_jobQ
#             - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
#             - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ           
#             - compare_git --path  $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ  --commit-range HEAD~2..HEAD
#             - update_commit_status sample_jobQ --status processing --message “my_status_is pushed” --context $STEP_NAME
#             - read_json secrets.json "LESSER_SECRET_FORMULA"
#              - write_output sample_jobW imageTag=v1.0.0
             
#             - replicate_resource sample_jobQ sample_jobW --match-settings
           # - replicate_resource sample_jobQ sample_jobW
# #             - popd
          onSuccess:
            - send_notification slack_bindu
          onFailure:
            - send_notification slack_bindu
          onComplete: #always
            - send_notification slack_bindu
#         outputResources:
#           - sample_jobW  

      - name: test2u18
        type: bash
        setup:
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18node
                tag: master
                options: "" 
#         configuration:
#           nodePool: kermit_ubuntu18_pool
        triggeredBy:
          steps:
            - test1u16
        requires:
          integrations:
            - slack_bindu
#         triggeredBy: 
#         requires:
          resources:
            - sample_jobQ
        execution:
          onStart:
            - printenv
            - echo "starting now"
          onExecute:
            - printenv
            - echo $env1
            - test $env1=val1
            
#             - pushd $res_sample_jobQ_resourcePath
#             - bump_semver v1.0.0 minor
#             - compare_git --resource sample_jobQ
#             - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
#             - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ 
#             - update_commit_status sample_jobQ --status success --message "my status push" --context $STEP_NAME
#             - read_json secrets.json "LESSER_SECRET_FORMULA"
#             - send_notification slack_bindu
#             - popd
          onSuccess:
            - send_notification slack_bindu
          onFailure:
            - send_notification slack_bindu
          onComplete: #always
            - send_notification slack_bindu
#           onCancel:
#             - send_notification slack_bindu

             
      - name: test3c7
        type: bash
#         configuration:
#           nodePool: kermit_centos_pool
        setup:
          runtime:            
            type: image
            image:
              custom:
                name: drydock/c7node
                tag: master
                options: "" 
        triggeredBy:
          steps:
            - test2u18
        requires:
          resources:
            - sample_jobQ 
          integrations:
            - slack_bindu
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
#             - pushd $res_sample_jobQ_resourcePath
#             - read_json secrets.json "LESSER_SECRET_FORMULA"
#             - popd

#             - docker images
#             - openssl genrsa -out key.pem 1024 
#             - bump_semver v1.0.0 minor
#             - compare_git --resource sample_jobQ
#             - compare_git --resource sample_jobQ --commit-range HEAD~2..HEAD
#             - compare_git --commit-range 92ba4f71fe362aafd9f3576453f0fd73b9e5adf3..master --path $STEP_DEPENDENCY_STATE_DIR/resources/sample_jobQ 
          onSuccess:
            - send_notification slack_bindu
          onFailure:
            - send_notification slack_bindu
          onComplete: #always
            - send_notification slack_bindu
