 # for git resources 
 
resources:
  - name: sample_jobQ 
    type: gitRepo
    repoPath: bindushree16/job_test
    configuration:
      integrationName: bindu_github
      branches:
        only: master
#       buildOn:
#         commit: false
    version:
      sha: master

pipelines:
  - name: pipelinejob
    steps:
      - name: test1u16
        type: bash
        triggeredBy:
          resources:
            - sample_jobQ
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - bump_semver v1.0.0-rc minor


#       - name: test2u18
#         type: bash
#         triggeredBy:
#           resources:
#             - sample_jobQ
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
            

#       - name: test3c7
#         type: bash 
#         requires:
#           resources:
#             - sample_jobQ
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - printenv
           
